// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logistic.Shared.Entites;

public partial class Direccion
{
    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// País ID
    /// </summary>
    public int? IdPais { get; set; }

    /// <summary>
    /// Tipo Dirección ID
    /// </summary>
    public int? IdTipoDireccion { get; set; }

    /// <summary>
    /// Tipo Via ID
    /// </summary>
    public int? IdTipoVia { get; set; }

    /// <summary>
    /// Tipo Zona ID
    /// </summary>
    public int? IdTipoZona { get; set; }

    /// <summary>
    /// Distrito ID
    /// </summary>
    public int? IdDistrito { get; set; }

    /// <summary>
    /// Nombre Vía
    /// </summary>
    public string ViaNombre { get; set; }

    /// <summary>
    /// Número Vía
    /// </summary>
    public string ViaNumero { get; set; }

    /// <summary>
    /// Nombre Zona
    /// </summary>
    public string ZonaNombre { get; set; }

    /// <summary>
    /// Dirección
    /// </summary>
    public string DireccionName { get; set; }

    /// <summary>
    /// Ubigeo
    /// </summary>
    public string UbigeoName { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Insert Fecha
    /// </summary>
    public DateTime AuditInsertFecha { get; set; }

    /// <summary>
    /// Auditoría Insert User
    /// </summary>
    public string AuditInsertUsuario { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public DateTime? AuditUpdateFecha { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public string AuditUpdateUsuario { get; set; }

    public virtual ICollection<Empresa> Empresa { get; set; } = new List<Empresa>();

    public virtual ICollection<EmpresaGrupos> EmpresaGrupos { get; set; } = new List<EmpresaGrupos>();

    public virtual ICollection<EmpresaLocal> EmpresaLocal { get; set; } = new List<EmpresaLocal>();

    public virtual UbigeoDistrito IdDistritoNavigation { get; set; }

    public virtual Paises IdPaisNavigation { get; set; }

    public virtual TipoDireccion IdTipoDireccionNavigation { get; set; }

    public virtual TipoVia IdTipoViaNavigation { get; set; }

    public virtual TipoZona IdTipoZonaNavigation { get; set; }
}