// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logistic.Shared.Entites;

public partial class EmpresaGrupos
{
    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// RUC
    /// </summary>
    public string NumeroRUC { get; set; }

    /// <summary>
    /// Razón Social
    /// </summary>
    public string RazonSocial { get; set; }

    /// <summary>
    /// Página Web
    /// </summary>
    public string PaginaWeb { get; set; }

    /// <summary>
    /// Dirección ID
    /// </summary>
    public int? IdDireccion { get; set; }

    /// <summary>
    /// Logo ID
    /// </summary>
    public int? IdLogoImagen { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Insert Fecha
    /// </summary>
    public DateTime AuditInsertFecha { get; set; }

    /// <summary>
    /// Auditoría Insert User
    /// </summary>
    public string AuditInsertUsuario { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public DateTime? AuditUpdateFecha { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public string AuditUpdateUsuario { get; set; }

    public virtual ICollection<Empresa> Empresa { get; set; } = new List<Empresa>();

    public virtual Direccion IdDireccionNavigation { get; set; }

    public virtual Imagenes IdLogoImagenNavigation { get; set; }
}