// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logistic.Shared.Entites;

public partial class Usuario
{
    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Código
    /// </summary>
    public string Codigo { get; set; }

    /// <summary>
    /// Descripción
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    public string Correo { get; set; }

    /// <summary>
    /// Celular
    /// </summary>
    public string Celular { get; set; }

    /// <summary>
    /// Clave
    /// </summary>
    public string Clave { get; set; }

    /// <summary>
    /// Foto ID
    /// </summary>
    public int? IdFoto { get; set; }

    /// <summary>
    /// Rol ID
    /// </summary>
    public int IdRol { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Insert Fecha
    /// </summary>
    public DateTime AuditInsertFecha { get; set; }

    /// <summary>
    /// Auditoría Insert User
    /// </summary>
    public string AuditInsertUsuario { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public DateTime? AuditUpdateFecha { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public string AuditUpdateUsuario { get; set; }

    public virtual Imagene IdFotoNavigation { get; set; }

    public virtual Role IdRolNavigation { get; set; }

    public virtual ICollection<UsuarioLocale> UsuarioLocales { get; set; } = new List<UsuarioLocale>();
}