// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Logistic.Shared.Entites;
using Microsoft.EntityFrameworkCore;

namespace Logistic.BackEnd.Data.Data;

public partial class LogisticContext : DbContext
{
    public LogisticContext(DbContextOptions<LogisticContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Direccion> Direccion { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    public virtual DbSet<EmpresaGrupos> EmpresaGrupos { get; set; }

    public virtual DbSet<EmpresaLocal> EmpresaLocal { get; set; }

    public virtual DbSet<Imagenes> Imagenes { get; set; }

    public virtual DbSet<Paises> Paises { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<TipoAlmacen> TipoAlmacen { get; set; }

    public virtual DbSet<TipoArticulo> TipoArticulo { get; set; }

    public virtual DbSet<TipoCalificacion> TipoCalificacion { get; set; }

    public virtual DbSet<TipoCambio> TipoCambio { get; set; }

    public virtual DbSet<TipoCompra> TipoCompra { get; set; }

    public virtual DbSet<TipoCuentaBancaria> TipoCuentaBancaria { get; set; }

    public virtual DbSet<TipoCuentaMayor> TipoCuentaMayor { get; set; }

    public virtual DbSet<TipoDireccion> TipoDireccion { get; set; }

    public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }

    public virtual DbSet<TipoDocumentoIdentidad> TipoDocumentoIdentidad { get; set; }

    public virtual DbSet<TipoFormaPago> TipoFormaPago { get; set; }

    public virtual DbSet<TipoMarcaArticulo> TipoMarcaArticulo { get; set; }

    public virtual DbSet<TipoMotivoBaja> TipoMotivoBaja { get; set; }

    public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }

    public virtual DbSet<TipoProceso> TipoProceso { get; set; }

    public virtual DbSet<TipoSocio> TipoSocio { get; set; }

    public virtual DbSet<TipoSolicitud> TipoSolicitud { get; set; }

    public virtual DbSet<TipoValorizacion> TipoValorizacion { get; set; }

    public virtual DbSet<TipoVia> TipoVia { get; set; }

    public virtual DbSet<TipoZona> TipoZona { get; set; }

    public virtual DbSet<UbigeoDepartamento> UbigeoDepartamento { get; set; }

    public virtual DbSet<UbigeoDistrito> UbigeoDistrito { get; set; }

    public virtual DbSet<UbigeoProvincia> UbigeoProvincia { get; set; }

    public virtual DbSet<UsuarioLocales> UsuarioLocales { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Direccion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Direccio__3214EC076A5F7908");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.DireccionName)
                .HasMaxLength(96)
                .IsUnicode(false)
                .HasComment("Dirección");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdDistrito).HasComment("Distrito ID");
            entity.Property(e => e.IdPais).HasComment("País ID");
            entity.Property(e => e.IdTipoDireccion).HasComment("Tipo Dirección ID");
            entity.Property(e => e.IdTipoVia).HasComment("Tipo Via ID");
            entity.Property(e => e.IdTipoZona).HasComment("Tipo Zona ID");
            entity.Property(e => e.UbigeoName)
                .HasMaxLength(96)
                .IsUnicode(false)
                .HasComment("Ubigeo");
            entity.Property(e => e.ViaNombre)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Nombre Vía");
            entity.Property(e => e.ViaNumero)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasComment("Número Vía");
            entity.Property(e => e.ZonaNombre)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Nombre Zona");

            entity.HasOne(d => d.IdDistritoNavigation).WithMany(p => p.Direccion)
                .HasForeignKey(d => d.IdDistrito)
                .HasConstraintName("FK_Direccion_UbigeoDistrito");

            entity.HasOne(d => d.IdPaisNavigation).WithMany(p => p.Direccion)
                .HasForeignKey(d => d.IdPais)
                .HasConstraintName("FK_Direccion_Paises");

            entity.HasOne(d => d.IdTipoDireccionNavigation).WithMany(p => p.Direccion)
                .HasForeignKey(d => d.IdTipoDireccion)
                .HasConstraintName("FK_Direccion_TipoDireccion");

            entity.HasOne(d => d.IdTipoViaNavigation).WithMany(p => p.Direccion)
                .HasForeignKey(d => d.IdTipoVia)
                .HasConstraintName("FK_Direccion_TipoVia");

            entity.HasOne(d => d.IdTipoZonaNavigation).WithMany(p => p.Direccion)
                .HasForeignKey(d => d.IdTipoZona)
                .HasConstraintName("FK_Direccion_TipoZona");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Empresa__3214EC071A3D0881");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdDireccion).HasComment("Dirección ID");
            entity.Property(e => e.IdGrupo).HasComment("Grupo ID");
            entity.Property(e => e.IdLogoImagen).HasComment("Logo ID");
            entity.Property(e => e.NumeroRUC)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("RUC");
            entity.Property(e => e.PaginaWeb)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Página Web");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Razón Social");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Empresa)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_Empresa_Direccion");

            entity.HasOne(d => d.IdGrupoNavigation).WithMany(p => p.Empresa)
                .HasForeignKey(d => d.IdGrupo)
                .HasConstraintName("FK_Empresa_EmpresaGrupos");

            entity.HasOne(d => d.IdLogoImagenNavigation).WithMany(p => p.Empresa)
                .HasForeignKey(d => d.IdLogoImagen)
                .HasConstraintName("FK_Empresa_Imagenes");
        });

        modelBuilder.Entity<EmpresaGrupos>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EmpresaG__3214EC0766C30F1C");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdDireccion).HasComment("Dirección ID");
            entity.Property(e => e.IdLogoImagen).HasComment("Logo ID");
            entity.Property(e => e.NumeroRUC)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("RUC");
            entity.Property(e => e.PaginaWeb)
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Página Web");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Razón Social");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.EmpresaGrupos)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_EmpresaGrupos_Direccion");

            entity.HasOne(d => d.IdLogoImagenNavigation).WithMany(p => p.EmpresaGrupos)
                .HasForeignKey(d => d.IdLogoImagen)
                .HasConstraintName("FK_EmpresaGrupos_Imagenes");
        });

        modelBuilder.Entity<EmpresaLocal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EmpresaL__3214EC077E1ADA85");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdDireccion).HasComment("Dirección ID");
            entity.Property(e => e.IdEmpresa).HasComment("Empresa ID");
            entity.Property(e => e.NumeroRUC)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("RUC");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false)
                .HasComment("Razón Social");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.EmpresaLocal)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("FK_EmpresaLocal_Direccion");

            entity.HasOne(d => d.IdEmpresaNavigation).WithMany(p => p.EmpresaLocal)
                .HasForeignKey(d => d.IdEmpresa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmpresaLocal_Empresa");
        });

        modelBuilder.Entity<Imagenes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Imagenes__3214EC0718872A14");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.ImagenArchivo).HasComment("Archivo");
            entity.Property(e => e.ImagenExtension)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("Extensión");
            entity.Property(e => e.ImagenNombre)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasComment("Nombre");
        });

        modelBuilder.Entity<Paises>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Paises__3214EC0768B18D6D");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07AB7E9447");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoAlmacen>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoAlma__3214EC0736E29B8A");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoArticulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoArti__3214EC074397039B");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Aud.Fch.Insert")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Aud.Fch.InsertUser");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoCalificacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoCali__3214EC07F417F360");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoCambio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoCamb__3214EC0771C57EF1");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.FechaOperacion).HasColumnType("date");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
            entity.Property(e => e.TipoOperacion)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ValorTipoCambio).HasColumnType("decimal(12, 6)");
        });

        modelBuilder.Entity<TipoCompra>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoComp__3214EC07A19E3465");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoCuentaBancaria>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoCuen__3214EC071CDA998C");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoCuentaMayor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoCuen__3214EC07465EFDDB");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoDireccion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoDire__3214EC0753EA705A");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoDocu__3214EC0795E6B3A4");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoDocumentoIdentidad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoDocu__3214EC07699345D3");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdCodigoSunat)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
            entity.Property(e => e.Simbolo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TipoFormaPago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoForm__3214EC078C1B120F");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoMarcaArticulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoMarc__3214EC07696CF1BB");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoMotivoBaja>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoMoti__3214EC0764A09313");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoMovimiento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoMovi__3214EC07E438A6A3");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.CodigoDetraccion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IngresoSalida)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
            entity.Property(e => e.TipoOperaccionSunat)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TipoProceso>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoProc__3214EC07C8946539");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoSocio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoSoci__3214EC075FF7F6B4");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoSolicitud>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoSoli__3214EC07AB9552EB");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoValorizacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoValo__3214EC073D8F9652");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoVia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoVia__3214EC070C41CC0B");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<TipoZona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TipoZona__3214EC079583E7C4");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<UbigeoDepartamento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UbigeoDe__3214EC078BEF15CB");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");
        });

        modelBuilder.Entity<UbigeoDistrito>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UbigeoDi__3214EC071A1AD2C0");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdProvincia).HasComment("Provincia ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.UbigeoDistrito)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UbigeoDistrito_UbigeoProvincia");
        });

        modelBuilder.Entity<UbigeoProvincia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UbigeoPr__3214EC0750B7E584");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Codigo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdDepartamento).HasComment("Departamento ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");

            entity.HasOne(d => d.IdDepartamentoNavigation).WithMany(p => p.UbigeoProvincia)
                .HasForeignKey(d => d.IdDepartamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UbigeoProvincia_UbigeoDepartamento");
        });

        modelBuilder.Entity<UsuarioLocales>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioL__3214EC071D970F78");

            entity.Property(e => e.Id).HasComment("Id");
            entity.Property(e => e.AuditInsertFecha)
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdLocal).HasComment("Local ID");
            entity.Property(e => e.IdUsuario).HasComment("Usuario ID");

            entity.HasOne(d => d.IdLocalNavigation).WithMany(p => p.UsuarioLocales)
                .HasForeignKey(d => d.IdLocal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioLocales_EmpresaLocal");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioLocales)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioLocales_Usuarios");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC073EC1A31C");

            entity.Property(e => e.Id).HasComment("ID");
            entity.Property(e => e.AuditInsertFecha)
                .HasDefaultValueSql("(getdate())")
                .HasComment("Auditoría Insert Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditInsertUsuario)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Insert User");
            entity.Property(e => e.AuditUpdateFecha)
                .HasComment("Auditoría Update Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.AuditUpdateUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Auditoría Update Fecha");
            entity.Property(e => e.Celular)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasComment("Celular");
            entity.Property(e => e.Clave)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasComment("Clave");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasComment("Código");
            entity.Property(e => e.Correo)
                .HasMaxLength(96)
                .IsUnicode(false)
                .HasComment("Email");
            entity.Property(e => e.EsActivo).HasComment("¿Es Activo?");
            entity.Property(e => e.IdFoto).HasComment("Foto ID");
            entity.Property(e => e.IdRol).HasComment("Rol ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("Descripción");

            entity.HasOne(d => d.IdFotoNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdFoto)
                .HasConstraintName("FK_Usuarios_Imagenes");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuarios_Roles");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}