// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logistic.Shared.DTO.Entites;

public partial class Imagene
{
    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Nombre
    /// </summary>
    public string ImagenNombre { get; set; }

    /// <summary>
    /// Extensión
    /// </summary>
    public string ImagenExtension { get; set; }

    /// <summary>
    /// Archivo
    /// </summary>
    public byte[] ImagenArchivo { get; set; }

    /// <summary>
    /// ¿Es Activo?
    /// </summary>
    public bool EsActivo { get; set; }

    /// <summary>
    /// Auditoría Insert Fecha
    /// </summary>
    public DateTime AuditInsertFecha { get; set; }

    /// <summary>
    /// Auditoría Insert User
    /// </summary>
    public string AuditInsertUsuario { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public DateTime? AuditUpdateFecha { get; set; }

    /// <summary>
    /// Auditoría Update Fecha
    /// </summary>
    public string AuditUpdateUsuario { get; set; }

    public virtual ICollection<EmpresaGrupo> EmpresaGrupos { get; set; } = new List<EmpresaGrupo>();

    public virtual ICollection<Empresa> Empresas { get; set; } = new List<Empresa>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}